services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '127.0.0.1:81:81' # Admin Web Port (localhost only - access via SSH tunnel)
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      TZ: "Europe/Lisbon"
      # Postgres parameters:
      DB_POSTGRES_HOST: 'db-nginx-proxy-manager'
      DB_POSTGRES_PORT: '5432'
      DB_POSTGRES_USER: ${DB_POSTGRES_USER:-'npm'}
      DB_POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD:-'npmpass'}
      DB_POSTGRES_NAME: ${DB_POSTGRES_NAME:-'npm'}
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      db-nginx-proxy-manager:
        condition: service_healthy      

  db-nginx-proxy-manager:
    image: postgres:17
    container_name: db-nginx-proxy-manager
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER:-'npm'}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD:-'npmpass'}
      POSTGRES_DB: ${DB_POSTGRES_NAME:-'npm'}
    volumes:
      - ./postgresql:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U npm"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s