version: "3"

services:
  api:
    image: ghcr.io/arubenruben/knowledge-base/laravel-dockerized-setup:stable
    restart: unless-stopped
    ports:
      - "8002:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - laravel-dockerized-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
networks:
  laravel-dockerized-network:    
    driver: bridge